### ISSUE TITLE
Build/Install fails.

### ISSUE THREAD

**Issue by ComedyTomedy** [Dentrax/GMDB#3]
Got a few type errors/warnings while building, and then install failed. I don't know enough about Go to begin to debug this; any help appreciated.

```$ go build .
# github.com/Dentrax/GMDB/pkg
../../.go/src/github.com/Dentrax/GMDB/pkg/gmdb.go:527:40: cannot use c.Args() (type cli.Args) as type []string in argument to strings.Join
../../.go/src/github.com/Dentrax/GMDB/pkg/gmdb.go:594:38: cannot use c.Args() (type cli.Args) as type []string in argument to strings.Join
../../.go/src/github.com/Dentrax/GMDB/pkg/gmdb.go:695:43: cannot use c.Args() (type cli.Args) as type []string in argument to strings.Join

$ go install .
go install: no install location for directory /home/username/GMDB outside GOPATH
	For more details see: 'go help gopath'
```

**Comment by Dentrax** [comment]
Thanks! It was throwing because of the [cli](https://github.com/urfave/cli) package has updated the own syntax in _2.X_ version, see [here](https://github.com/urfave/cli/releases). Now, this error fixed in: https://github.com/Dentrax/GMDB/commit/dd036bd5f14e100007b4fc2200eb191fad77536e

And also, looks like you didn't set your _GOPATH_ env. In this case, you may need to set your path, which is already written [here](https://github.com/golang/go/wiki/SettingGOPATH).
